#ifndef ALORA_CONNIO_CONSTANTS_H
#define ALORA_CONNIO_CONSTANTS_H

#define GAS_SENSOR_HEAT_PIN 17
#define GAS_SENSOR_ADC_CHANNEL 0

#define SOUND_SENSOR_ADDRESS 0x2f
#define SOUND_SENSOR_ADC_CHANNEL 1
#define SOUND_SENSOR_R 51000

#define LSM9DS0_XM_ADDRESS 0x1d
#define LSM9DS0_G 0x6b

#define DISPLAY_ENABLED 0

#endif
